### ISSUE TITLE
Returned frequency values

### ISSUE THREAD

**Issue by jackgoffinet** [neil-gallagher/directed-spectrum#6]
Right now the returned frequency values run from zero to the nyquist frequency and then jump to the negative nyquist frequency back up to zero. I know this is a convention for discrete Fourier transforms, but it may be easier to use and less redundant by just returning the nonnegative frequencies like `scipy.signal.stft`.

**Comment by neil-gallagher** [comment]
Hey Jack, I'm just getting around to this now, sorry for the long delay. Are there any real applications you're interested in where you'd need to calculate the directed spectrum for a complex signal? I'm planning to add an option to return a one-sided result and may make it the default if there aren't any common use cases that require complex input.

Also do you remember if the real and imaginary components of the signal you input had a nonzero cross-spectral density? I think that's the only case where you'd expect a non-symmetric output.

**Comment by neil-gallagher** [comment]
OK, I've added an option for returning a one-sided spectrum, but I'm not making it the default behavior for now so as to not break any stuff you guys have already written based on the two-sided output
